# Generated by Django 4.2.3 on 2023-07-29 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='الاسم :')),
                ('subtitle', models.CharField(max_length=300, verbose_name='نبذة عنك')),
                ('address', models.CharField(max_length=50, verbose_name='المحافظة :')),
                ('address_detail', models.CharField(max_length=100, verbose_name='العنوان بالتفصيل :')),
                ('number_phone', models.CharField(max_length=50, verbose_name='الهاتف :')),
                ('working_hours', models.CharField(max_length=50, verbose_name='عدد ساعات العمل :')),
                ('waiting_time', models.IntegerField(blank=True, null=True, verbose_name='مدة الانتظار :')),
                ('doctor', models.CharField(blank=True, max_length=50, null=True, verbose_name='دكتور؟')),
                ('who_i', models.TextField(blank=True, max_length=250, null=True, verbose_name='من انا :')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='سعر الكشف :')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('google', models.CharField(blank=True, max_length=100, null=True)),
                ('specialist_doctor', models.CharField(blank=True, max_length=100, null=True, verbose_name='متخصص في؟')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
