# Generated by Django 4.2.3 on 2023-07-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_tye_of_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=50, null=True, verbose_name='دكتور؟'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tye_of_person',
            field=models.CharField(choices=[('جلدية', 'جلدية'), ('أسنان', 'أسنان'), ('نفسي', 'نفسي'), ('أطفال حديثي الولادة', 'أطفال حديثي الولادة'), ('مخ و أعصاب', 'مخ و أعصاب'), ('عظام', 'عظام'), ('نساء و توليد', 'نساء و توليد'), ('أنف و أذن و حنجرة', 'أنف و أذن و حنجرة'), ('قلب و أوعية دموية ', 'قلب و أوعية دموية'), ('أمراض دم', 'أمراض دم'), ('أورام', 'أورام'), ('باطنة', 'باطنة'), ('تخسيس و تغذية', 'تخسيس و تغذية'), ('جراحة أطفال', 'جراحة أطفال'), ('جراحة أورام', 'جراحة أورام'), ('جراحة أوعية دموية', 'جراحة أوعية دموية'), ('جراحة تجميل', 'جراحة تجميل'), ('جراحة سمنة و مناظير', 'جراحة سمنة و مناظير')], max_length=50, verbose_name='النوع :'),
        ),
    ]
