# Generated by Django 4.2.3 on 2023-07-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='', upload_to='profile', verbose_name='الصورة الشخصية'),
            preserve_default=False,
        ),
    ]
