# Generated by Django 4.2.3 on 2023-07-28 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profiles', 'verbose_name_plural': 'Profiles'},
        ),
    ]
